import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { CartProvider } from "@/context/CardContext"; // CartProvider sudah ada
// Misalkan Anda juga menambahkan provider untuk tema atau pengguna
import { ThemeProvider } from "@/context/ThemeContext";  // Contoh ThemeContext
import { UserProvider } from "@/context/UserContext";  // Contoh UserContext
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Membungkus children dengan beberapa provider */}
        <CartProvider>
          <ThemeProvider>  {/* Menambahkan ThemeProvider */}
            <UserProvider> {/* Menambahkan UserProvider */}
              {children}
            </UserProvider>
          </ThemeProvider>
        </CartProvider>
      </body>
    </html>
  );
}
